name: PetClinic POC

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    # Installed software
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2-beta
#      with:
#        path: ~/work/

    - name: List workspace
      working-directory: ${{ github.workspace }}
      run: ls -la

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # https://github.com/actions/cache/blob/master/examples.md
    - name: Cache local Maven repo
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Build with Maven
      run: mvn install -Dmaven.test.skip=true --file pom.xml

    - name: Run unit tests
      run: mvn test

#    - name: Archive test results
#      uses: actions/upload-artifact@v1
#      with:
#        name: unit-tests
#        path: target/surefire-reports/*.**
